### ISSUE TITLE
Questions - performance and interpretation

### ISSUE THREAD

**Issue by richardbeare** [Inria-Asclepios/simul-atrophy#4]
Hello,

I am investigating simul-atrophy and have some questions about optimizing performance and interpreting results.

1. Performance: I have the tools running in a singularity container on an HPC system. Various petsc documents suggest that mpi functionality is available. Has simulatrophy been written to take advantage of mpi or other multithreading? I observe multiple core usage if I run the container with an mpi option, but I don't see a reduction in run time. Is this expected, or have I perhaps missed something during the configuration process?

1. Interpretation: I am using baseline scans from ADNI, with both freesurfer and spm tissue maps to set up my generation of new images, with a command line a follows:
```bash
simul_atrophy -parameters 1,1,1,1 -boundary_condition dirichlet_at_skull --relax_ic_in_csf -atrophyFile ${ATROFILE} -maskFile ${TD}/${ID}_comb.nii.gz -imageFile ${RAWDIR}/${ID}.nii.gz --invert_field_to_warp -numOfTimeSteps $STEPS -resPath $DEST -resultsFilenamesPrefix ${ID}_
```

where ATROFILE is generated by `create_atrophy_map.py` based on the freesurfer aparc+aseg and a version of `atrophyTableCarmiWithPercentage` with all values set to a constant (various tests cover 0, 0.01, 0.05 and 0.10)

maskFile is wm/gm mask from spm.

How should I interpret the values in the atrophy table? They don't appear to be
percentages? I am unsure which parameters in the various papers they correspond to.

A summary of the results of applying freesurfer to the output images is below. The pink dot, t0, corresponds to the thickness estimate resulting from freesurfer applied to the original scan that was provided to simulatrophy. I assume that changes in noise characteristics have changed the freesurfer estimate relative to the 0 atrophy version.

If I estimate the slope of each line via regression I get the following:

- atrophy = 0.01, slope = -4.496500e-03
- atrophy = 0.05, slope = -2.535250e-02
- atrophy = 0.10, slope = -3.459800e-02

These input and output atrophy values don't h, although they they are similar orders of magnitude. Thus I suspect that I need some guidance on how to interpret the input atrophy value.

Thanks!

![atrophy](https://user-images.githubusercontent.com/780449/72942210-ff0bbe00-3dc6-11ea-94ac-f2116095e341.png)

**Comment by bishesh** [comment]
Hi Richard,
1. Simul@atrophy uses petsc and its mpi functionality. It primarily calls petsc solvers and preconditioner to solve the PDE. For small sized grids, the benefit won't be seen. If you have a large grid, then I think you should be seeing the speed-up. The code is written in order to let pets use its mpi functionality. However, some parts such as going from ITK image to petsc format and coming back to ITK format are not parallelized and we won't see the speed up here.

2. The atrophy values in `atrophyTableCarmiWithPercentage` are the percentage change (V_0-V_1)/V_0 taken from Table 3 of [Carmichael2013](https://www.sciencedirect.com/science/article/abs/pii/S1053811912010324). The values in atrophy table refer to parameter `a` in [Khanal2016](https://www.ncbi.nlm.nih.gov/pubmed/27039699). The detailed derviation of the equations can be found in the appendix of the [PhD thesis](https://tel.archives-ouvertes.fr/tel-01384678/document). 

3. The input and output atrophy: If you compute the divergence of the velocity field obtained during the simulation, output atrophy, it is exactly equal to the input atrophy point-wise i.e. at each voxel. However, when you use one of the many atrophy estimation methods,  the estimated atrophy is not necessarily equal to input atrophy. 
`a` is a point-wise local atrophy from the deformation field. When we estimate atrophy, we take image intensity which is a result of applying the deformation field to the input image. This process + the assumptions and accuracy of the estimation method used (e.g. FreeSurfer, BSI, registration based methods) will have an impact on the output estimated atrophy.
[Sivera2019](https://www.sciencedirect.com/science/article/abs/pii/S105381191930432X) discusses this, showing bias in estimation using registration based methods but still more reproducible than segmentation based methods (Sec 4.1.2 Model estimation).

**Comment by richardbeare** [comment]
Excellent - thankyou!
